[package]
name = "user_lib"
version = "0.1.0"
authors = ["dhz write fllow rCore-tutorial-v3"]
edition = "2018" 



[dependencies]
riscv = { git = "https://github.com/rcore-os/riscv", features = ["inline-asm"] } 